import { setupI18n } from '@lingui/core';

// this file is generated by the cli
import enMessages from './locale/en/messages.json';
import frMessages from './locale/fr/messages.json';

// import this constant as get translations from it outside of React
export const i18n = setupI18n({
  language: 'en',
  catalogs: {
    en: enMessages,
    fr: frMessages,
  },
});
