export enum Routes {
  HistoryOverview = 'HistoryOverview',
  Dashboard = 'Dashboard',
  MyWorkouts = 'MyWorkouts',
  WorkoutEditor = 'WorkoutEditor',
  ExercisesChoice = 'ExercisesChoice',
  ExercisesNavigator = 'ExercisesNavigator',
  WorkoutsNavigator = 'WorkoutsNavigator',
  HomeNavigator = 'HomeNavigator',
  HistoryNavigator = 'HistoryNavigator',
  TabNavigator = 'TabNavigator',
  OngoingWorkoutOverview = 'OngoingWorkoutOverview',
  OngoingWorkout = 'OngoingWorkout',
  HistoryDetails = 'HistoryDetails',
  Login = 'Login',
  Signup = 'Signup',
  MyProfile = 'MyProfile',
  ProfileNavigator = 'ProfileNavigator',
  TrainingNavigator = 'TrainingNavigator',
  TrainingCreation = 'TrainingCreation',
  TrainingSets = 'TrainingSets',
  TrainingName = 'TrainingName',
  TrainingTags = 'TrainingTags',
  ExerciseNavigator = 'ExerciseNavigator',
  ExerciseName = 'ExerciseName',
  ExerciseMuscleGroups = 'ExerciseMuscleGroups',
}
