"use strict";
exports.__esModule = true;
var Routes;
(function (Routes) {
    Routes["HistoryOverview"] = "HistoryOverview";
    Routes["Dashboard"] = "Dashboard";
    Routes["MyWorkouts"] = "MyWorkouts";
    Routes["WorkoutEditor"] = "WorkoutEditor";
    Routes["ExercisesChoice"] = "ExercisesChoice";
    Routes["ExercisesNavigator"] = "ExercisesNavigator";
    Routes["WorkoutsNavigator"] = "WorkoutsNavigator";
    Routes["HomeNavigator"] = "HomeNavigator";
    Routes["HistoryNavigator"] = "HistoryNavigator";
    Routes["TabNavigator"] = "TabNavigator";
    Routes["OngoingWorkoutOverview"] = "OngoingWorkoutOverview";
    Routes["OngoingWorkout"] = "OngoingWorkout";
    Routes["HistoryDetails"] = "HistoryDetails";
    Routes["Login"] = "Login";
    Routes["Signup"] = "Signup";
    Routes["MyProfile"] = "MyProfile";
    Routes["ProfileNavigator"] = "ProfileNavigator";
    Routes["TrainingNavigator"] = "TrainingNavigator";
    Routes["TrainingCreation"] = "TrainingCreation";
    Routes["TrainingSets"] = "TrainingSets";
    Routes["TrainingName"] = "TrainingName";
    Routes["TrainingTags"] = "TrainingTags";
    Routes["ExerciseNavigator"] = "ExerciseNavigator";
    Routes["ExerciseName"] = "ExerciseName";
    Routes["ExerciseMuscleGroups"] = "ExerciseMuscleGroups";
})(Routes = exports.Routes || (exports.Routes = {}));
