export enum Routes {
  HistoryOverview = 'HistoryOverview',
  Dashboard = 'Dashboard',
  MyWorkouts = 'MyWorkouts',
  WorkoutEditor = 'WorkoutEditor',
  ExercisesChoice = 'ExercisesChoice',
  NewExercise = 'NewExercise',
  ExercisesNavigator = 'ExercisesNavigator',
  WorkoutsNavigator = 'WorkoutsNavigator',
  HomeNavigator = 'HomeNavigator',
  HistoryNavigator = 'HistoryNavigator',
  TabNavigator = 'TabNavigator',
  OngoingWorkoutOverview = 'OngoingWorkoutOverview',
  OngoingWorkout = 'OngoingWorkout',
  HistoryDetails = 'HistoryDetails',
  Login = 'Login',
  MyProfile = 'MyProfile',
  ProfileNavigator = 'ProfileNavigator',
}
